// File generated by FlutterFire CLI.
// DO NOT EDIT. This file is used by FlutterFire to configure your
// Flutter application with Firebase.

// For more information, visit the FlutterFire documentation at https://firebase.flutter.dev

import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.macOS)) {
      return macos;
    }
    if (kIsWeb) {
      return web;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.windows)) {
      return windows;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.linux)) {
      return linux;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqo0MdtfnDv-yDLI4wqzcTJgPfc6jSdrw',
    appId: '1:584111037389:android:cb47357becf69ec6ae0284',
    messagingSenderId: '584111037389',
    projectId: 'agoralink-276ea',
    databaseURL: 'https://agoralink-276ea-default-rtdb.firebaseio.com',
  );

//TODO: Replace the placeholder values with your actual Firebase project configuration values for iOS, macOS, web, windows, and linux platforms. You can find these values in your Firebase project settings.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqo0MdtfnDv-yDLI4wqzcTJgPfc6jSdrw',
    appId: '1:584111037389:ios:cb47357becf69ec6ae0284',
    messagingSenderId: '584111037389',
    projectId: 'agoralink-276ea',
    databaseURL: 'https://agoralink-276ea-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.agoralink',
  );

//TODO: Replace the placeholder values with your actual Firebase project configuration values for iOS, macOS, web, windows, and linux platforms. You can find these values in your Firebase project settings.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqo0MdtfnDv-yDLI4wqzcTJgPfc6jSdrw',
    appId: '1:584111037389:ios:cb47357becf69ec6ae0284',
    messagingSenderId: '584111037389',
    projectId: 'agoralink-276ea',
    databaseURL: 'https://agoralink-276ea-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.agoralink',
  );

//TODO: Replace the placeholder values with your actual Firebase project configuration values for iOS, macOS, web, windows, and linux platforms. You can find these values in your Firebase project settings.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqo0MdtfnDv-yDLI4wqzcTJgPfc6jSdrw',
    appId: '1:584111037389:web:cb47357becf69ec6ae0284',
    messagingSenderId: '584111037389',
    projectId: 'agoralink-276ea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqo0MdtfnDv-yDLI4wqzcTJgPfc6jSdrw',
    appId: '1:584111037389:windows:cb47357becf69ec6ae0284',
    messagingSenderId: '584111037389',
    projectId: 'agoralink-276ea',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCqo0MdtfnDv-yDLI4wqzcTJgPfc6jSdrw',
    appId: '1:584111037389:linux:cb47357becf69ec6ae0284',
    messagingSenderId: '584111037389',
    projectId: 'agoralink-276ea',
  );
}
